//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHold
    {
        public int ID { get; set; }
        public Nullable<System.Guid> QRUniqueID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string NumberOfPersons { get; set; }
        public string DOORNo { get; set; }
    }
}
