//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MicRecording
    {
        public int Id { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public System.DateTime DateTimeRecorded { get; set; }
        public bool IsRead { get; set; }
        public byte[] RecordedData { get; set; }
        public Nullable<int> LengthOfAudio { get; set; }
    
        public virtual VehiclesForMic VehiclesForMic { get; set; }
    }
}
