//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalMixedWastage
    {
        public int MixedWastageId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<decimal> MixedWasteCollected { get; set; }
        public Nullable<decimal> TotalMixedWasteDisposed { get; set; }
        public Nullable<decimal> MixedWasteRecovery { get; set; }
        public Nullable<int> HousesCollected { get; set; }
    }
}
