//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Nullable<System.DateTime> DateandTime { get; set; }
        public int NoOfTrips { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<int> NoofWorkers { get; set; }
        public string DriveName { get; set; }
        public Nullable<bool> CountTrueOrFalse { get; set; }
    }
}
