//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WastageConfirmation
    {
        public int WastageConfirmationId { get; set; }
        public System.DateTime Datetime { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> HouseId { get; set; }
        public Nullable<bool> ServiceGiven { get; set; }
        public Nullable<bool> IsScannestatus { get; set; }
        public Nullable<int> Trip { get; set; }
    }
}
